package studio.atopthehill.osom.data.db.dao // Package declaration for the DAO

import androidx.room.Dao // Room annotation for Data Access Object
import androidx.room.Insert // Room annotation for insert operations
import androidx.room.OnConflictStrategy // Room conflict strategy for inserts
import androidx.room.Query // Room annotation for custom SQL queries
import kotlinx.coroutines.flow.Flow // Kotlin Coroutines Flow for asynchronous data streams
import studio.atopthehill.osom.data.db.entity.AppUsage // Importing the AppUsage entity

@Dao // Marks the interface as a Data Access Object
interface AppUsageDao { // Defines the DAO interface for AppUsage entities

        @Insert(
                onConflict = OnConflictStrategy.IGNORE
        ) // Annotation for inserting AppUsage, ignores if conflict (e.g., unique constraint
        // violation,
        // though id is autogenerated)
        suspend fun insertAppUsage(
                appUsage: AppUsage
        ): Long // Suspended function to insert a single app usage record, returns the new rowId

        @Query(
                "SELECT * FROM app_usage WHERE package_name = :packageName ORDER BY timestamp DESC"
        ) // SQL query to select all usage records for a specific app, ordered by most recent
        fun getUsageForApp(
                packageName: String
        ): Flow<List<AppUsage>> // Function returning a Flow of AppUsage list for a given package
        // name

        @Query(
                "SELECT * FROM app_usage ORDER BY timestamp DESC"
        ) // SQL query to select all usage records, ordered by most recent
        fun getAllUsageRecords():
                Flow<List<AppUsage>> // Function returning a Flow of all AppUsage list

        @Query(
                "DELETE FROM app_usage WHERE id = :usageId"
        ) // SQL query to delete a specific usage record by its ID
        suspend fun deleteAppUsageRecord(
                usageId: Long
        ) // Suspended function to delete a specific app usage entry

        @Query(
                "DELETE FROM app_usage WHERE package_name = :packageName"
        ) // SQL query to delete all usage records for a specific app
        suspend fun clearUsageForApp(
                packageName: String
        ) // Suspended function to clear all usage history for a particular app

        @Query("DELETE FROM app_usage") // SQL query to delete all usage records from the table
        suspend fun clearAllUsage() // Suspended function to clear the entire app_usage table
}
